"""
Planner - Task decomposition and plan management.

Provides:
- Task planning via LLM
- Template-based planning for common tasks
- Plan execution tracking
- Plan optimization
"""

import json

from opennova.planning.models import COMMON_TEMPLATES, PlanTemplate
from opennova.providers.base import BaseLLMProvider, Message
from opennova.runtime.state import Plan, PlanStep

TEMPLATE_PREFERRED_KEYWORDS = {
    "unit test",
    "unit tests",
    "write tests",
    "add tests",
    "testing",
    "generate docs",
    "documentation",
    "docstring",
    "docstrings",
}


PLANNING_PROMPT = """You are a task planning assistant. Your job is to break down tasks into clear, actionable steps.

Given a task, create a structured plan with the following format:
```json
{{
    "task_summary": "Brief description of the task",
    "steps": [
        {{
            "id": "step_1",
            "description": "Clear description of what to do",
            "tool_hint": "suggested tool name (optional)"
        }}
    ]
}}
```

Guidelines:
1. Each step should be a single, focused action
2. Steps should be in logical execution order
3. Include tool hints when a specific tool is clearly needed
4. Keep descriptions concise but actionable
5. Usually 3-7 steps is appropriate

Task: {task}

Create a plan for this task. Respond ONLY with the JSON object.
"""


class Planner:
    """
    Plans and manages task execution.

    Features:
    - LLM-powered task decomposition
    - Template-based planning for common patterns
    - Plan tracking and status updates
    """

    def __init__(
        self,
        llm: BaseLLMProvider,
        use_templates: bool = True,
    ):
        """
        Initialize planner.

        Args:
            llm: LLM provider for planning
            use_templates: Whether to use plan templates
        """
        self.llm = llm
        self.use_templates = use_templates
        self.templates = COMMON_TEMPLATES.copy()

    def add_template(self, template: PlanTemplate) -> None:
        """Add a custom plan template."""
        self.templates.append(template)

    async def create_plan(self, task: str) -> Plan:
        """
        Create a plan for a task.

        Prefer LLM-authored plans for broad development requests, while keeping
        templates available for narrowly-scoped template-friendly tasks and as
        a fallback when LLM planning fails.

        Args:
            task: Task description

        Returns:
            Plan with steps
        """
        preferred_template = self._select_template(task)
        if preferred_template and self._should_prefer_template(task):
            return preferred_template.create_plan(task)

        llm_plan = await self._create_llm_plan(task)
        if self._is_fallback_plan(llm_plan, task) and preferred_template:
            return preferred_template.create_plan(task)

        return llm_plan

    def _select_template(self, task: str) -> PlanTemplate | None:
        """Return the first matching template for a task, if any."""
        if not self.use_templates:
            return None

        for template in self.templates:
            if template.matches(task):
                return template

        return None

    def _should_prefer_template(self, task: str) -> bool:
        """Whether a task is narrow enough to prefer a canned template."""
        task_lower = task.lower()
        return any(keyword in task_lower for keyword in TEMPLATE_PREFERRED_KEYWORDS)

    def _is_fallback_plan(self, plan: Plan, task: str) -> bool:
        """Detect the single-step fallback plan shape used when planning fails."""
        return (
            plan.task == task
            and len(plan.steps) == 1
            and plan.steps[0].id == "step_1"
            and plan.steps[0].description == task
        )

    async def _create_llm_plan(self, task: str) -> Plan:
        """
        Create a plan using LLM.

        Args:
            task: Task description

        Returns:
            Plan generated by LLM
        """
        prompt = PLANNING_PROMPT.format(task=task)

        messages = [
            Message(
                role="system",
                content="You are a helpful task planning assistant. Always respond with valid JSON.",
            ),
            Message(role="user", content=prompt),
        ]

        try:
            response = await self.llm.chat(messages, temperature=0.7)
            plan = self._parse_plan_response(response.content, task)
            return plan
        except Exception:
            return self._create_fallback_plan(task)

    def _parse_plan_response(self, response: str, task: str) -> Plan:
        """
        Parse LLM response into a Plan.

        Args:
            response: LLM response text
            task: Original task description

        Returns:
            Parsed Plan
        """
        json_str = response

        import re

        json_patterns = [
            r"```json\s*(.*?)\s*```",
            r"```\s*(.*?)\s*```",
            r"(\{.*\})",
        ]

        for pattern in json_patterns:
            match = re.search(pattern, response, re.DOTALL)
            if match:
                json_str = match.group(1)
                break

        try:
            data = json.loads(json_str)
        except json.JSONDecodeError:
            return self._create_fallback_plan(task)

        steps = []
        for i, step_data in enumerate(data.get("steps", [])):
            step = PlanStep(
                id=step_data.get("id", f"step_{i + 1}"),
                description=step_data.get("description", ""),
                tool_hint=step_data.get("tool_hint"),
            )
            steps.append(step)

        if not steps:
            return self._create_fallback_plan(task)

        task_summary = data.get("task_summary", task)

        return Plan(
            task=task_summary,
            steps=steps,
        ).reindex_steps()

    def _create_fallback_plan(self, task: str) -> Plan:
        """
        Create a simple fallback plan.

        Args:
            task: Task description

        Returns:
            Simple single-step plan
        """
        return Plan(
            task=task,
            steps=[
                PlanStep(
                    id="step_1",
                    description=task,
                )
            ],
        ).reindex_steps()

    def optimize_plan(self, plan: Plan) -> Plan:
        """
        Optimize a plan by merging similar steps.

        Args:
            plan: Plan to optimize

        Returns:
            Optimized plan
        """
        if len(plan.steps) <= 3:
            return plan.reindex_steps()

        optimized_steps = []
        merged = set()

        for i, step in enumerate(plan.steps):
            if i in merged:
                continue

            current_step = step

            for j in range(i + 1, len(plan.steps)):
                if j in merged:
                    continue

                next_step = plan.steps[j]

                if (
                    current_step.tool_hint
                    and next_step.tool_hint
                    and current_step.tool_hint == next_step.tool_hint
                ):
                    current_step = PlanStep(
                        id=current_step.id,
                        description=f"{current_step.description}; then {next_step.description.lower()}",
                        tool_hint=current_step.tool_hint,
                    )
                    merged.add(j)

            optimized_steps.append(current_step)

        return Plan(task=plan.task, steps=optimized_steps).reindex_steps()

    def get_next_step(self, plan: Plan) -> PlanStep | None:
        """
        Get the next pending step from a plan.

        Args:
            plan: Plan to check

        Returns:
            Next pending step or None
        """
        return plan.get_next_step()

    def estimate_plan_complexity(self, plan: Plan) -> str:
        """
        Estimate the complexity of a plan.

        Args:
            plan: Plan to analyze

        Returns:
            Complexity rating (simple/medium/complex)
        """
        num_steps = len(plan.steps)

        if num_steps <= 3:
            return "simple"
        elif num_steps <= 6:
            return "medium"
        else:
            return "complex"

    def get_plan_summary(self, plan: Plan) -> str:
        """
        Get a human-readable summary of a plan.

        Args:
            plan: Plan to summarize

        Returns:
            Summary string
        """
        lines = [f"📋 Plan: {plan.task}", ""]

        status_icons = {
            "pending": "⏳",
            "running": "🔄",
            "done": "✅",
            "failed": "❌",
            "skipped": "⏭️",
        }

        for step in plan.steps:
            icon = status_icons.get(step.status.value, "❓")
            lines.append(f"  {icon} {step.id}: {step.description}")
            if step.tool_hint:
                lines.append(f"     Tool: {step.tool_hint}")

        completed = sum(1 for s in plan.steps if s.status.value == "done")
        total = len(plan.steps)

        lines.append("")
        lines.append(f"Progress: {completed}/{total} steps completed")

        return "\n".join(lines)
